language: python

sudo: false

python:
  - "3.5"
  - "3.6"

install:
  - "pip install nose-exclude"
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install -e ."
  
script: 
  - nosetests --exclude-dir=generator
  - coverage run --source=pyidf --omit='*/generator/*,*/tests/*' -m nose --exclude test_class

after_success:
  - coveralls